# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/focal64"

    # Provider Settings
    config.vm.provider "virtualbox" do |vb|
	   vb.customize [ "modifyvm", :id, "--uartmode1", "file", File::NULL ]
       vb.memory = 2048
       vb.cpus = 4
    end
  
    # Network Settings
     config.vm.network "forwarded_port", guest: 80, host: 8080
    # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    # config.vm.network "private_network", ip: "192.168.33.10"
  
    # Folder Settings
    config.vm.synced_folder ".", "/HermanCode", :mount_options => ["dmode=777", "fmode=666"] 
    
    config.vm.provision "shell", path: "bootstrap.sh"
  end
